# Basic config
## Menu
menu:
  Computers: /computer
  # Essay: /essay
  # Dynamic: /dynamic
  # Share: /share
  # Guestbook: /guestbook
  # Custom Menu
  # example:
  #   [O]  About: /about/index  (directory based)
  #   [O]  About: /about        (single .md file)

# Slider
slider: 10 # unit: seconds. `true` or number for enable and `false` for disable
# Topic
topic:  # tag array for enable and `false` for disable
# example:
#   [0] - essay
#       - note
#   [x] - false
#   [x] true

## RSS Feed
## docs: https://github.com/hexojs/hexo-generator-feed
rss:
  enable: false
  # path: # path to atom.xml or rss.xml
 
## Social links
social:
   github: https://github.com/GuideFourthW
   twitter: https://twitter.com/fangu_one
  # websites:
    # - text: ...
    #   link: ...

## Sidebar
sidebar:
  leaf: To descript your blog. *Markdown* supported.
  github: GuideFourthW

## comments
### gitalk docs: https://github.com/gitalk/gitalk
### gitment docs: https://github.com/imsun/gitment
### valine docs: https://github.com/xCss/Valine
comments:
  enable: true
  engine: gitalk
  gitalk:
    # required: github application client id
    clientID: 1a4f86b4e3d4fbf65915
    # required: github application client secret
    clientSecret: 1458a58dda754c72b82d12845f47e8f8cc657dbd
    repo: GuideFourthW.github.io   # required: github repo
    owner: GuideFourthW # required: github repo owner
    admin: GuideFourthW  # required: gitHub repo owner and collaborators
                            # only these guys can initialize github issues
  gitment:
    repo: process.env.repo    # required: github repo
    owner: process.env.author # required: github repo owner
    oauth:
      # required: github application client id
      client_id: process.env.clientId
      # required: github application client secret
      client_secret: process.env.clientSecret
  valine:
    # required: leancloud app id
    appId: process.env.appId
    # required: leancloud app key
    appKey: process.env.appKey

## Build-in Search
## NOTE: DONNT USE NOW!!! -- TOO BUGGY
# search:
#   enable: false
#   engine: build-in  # only support build-in currently
#   max: 5            # the number of suggestions

auto_excerpt:
  enable: true
  length: 4
  
## powered by information
powered_by:
  author: GuideFourthW
  link: https://github.com/GuideFourthW

# External
## Google Analytics
google_analytics:
  enable: true
  track_id:  UA-142857803-1
